blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/kevin-lee/stui/discussions
    about: Please ask and answer questions, share ideas or show off your work here.
