package ucdgen

import java.nio.file.{Path, Paths}

final case class Output(path: Path, content: String)

/** Renders the generated Scala sources. Only simple shapes are emitted so the output is stable under scalafmt. */
object Emit {

  val ValueChunkSize: Int = 8192

  val LineChunkSize: Int = 16000

  val MaxValue: Int = 0xffff - 0x20

  val Eol: String = "\n"

  val MaxColumn: Int = 140

  val CodePointTablePath: Path =
    Paths.get("modules", "stui-unicode", "shared", "src", "main", "scala", "stui", "unicode", "internal", "CodePointTable.scala")

  val GraphemeBreakTestCorpusPath: Path =
    Paths.get("modules", "stui-unicode", "shared", "src", "test", "scala", "stui", "unicode", "corpus", "GraphemeBreakTestCorpus.scala")

  val EmojiTestCorpusPath: Path =
    Paths.get("modules", "stui-unicode", "shared", "src", "test", "scala", "stui", "unicode", "corpus", "EmojiTestCorpus.scala")

  val RawRangesPath: Path =
    Paths.get("modules", "stui-unicode", "jvm", "src", "test", "scala", "stui", "unicode", "internal", "RawRanges.scala")

  val TableSources: List[String] =
    List("DerivedCoreProperties.txt", "EastAsianWidth.txt", "GraphemeBreakProperty.txt", "PropList.txt", "emoji-data.txt")

  /** A value `v` (0 <= v <= MaxValue) as the literal text of the char `v + 0x20`: raw when printable ASCII, else `\uXXXX`. */
  def encodeValue(v: Int): String = {
    val c = v + 0x20
    if (c >= 0x20 && c <= 0x7e && c != '"'.toInt && c != '\\'.toInt) c.toChar.toString else f"\\u$c%04X"
  }

  def valueChunks(values: Seq[Int]): List[String] =
    values.grouped(ValueChunkSize).map(chunk => chunk.map(encodeValue).mkString).toList

  /** The literal text of a corpus character: printable ASCII raw (with `"` and `\` escaped), newline as `\n`, else `\uXXXX`. */
  def escapeChar(c: Char): String =
    c match {
      case '"' => "\\\""
      case '\\' => "\\\\"
      case '\n' => "\\n"
      case printable if c >= 0x20 && c <= 0x7e => printable.toString
      case other => f"\\u${other.toInt}%04X"
    }

  def escape(s: String): String = s.map(escapeChar).mkString

  /** Lines joined with `\n` (each chunk ends with one), cut on line boundaries at about LineChunkSize characters. */
  def lineChunks(lines: List[String]): List[String] = {
    val (done, current, _) = lines.foldLeft((Vector.empty[String], Vector.empty[String], 0)) {
      case ((done, current, size), line) =>
        val added = line.length + 1
        if (current.nonEmpty && size + added > LineChunkSize) (done :+ current.mkString("", Eol, Eol), Vector(line), added)
        else (done, current :+ line, size + added)
    }
    (if (current.isEmpty) done else done :+ current.mkString("", Eol, Eol)).toList
  }

  def header(manifest: Manifest, sources: List[String]): String = {
    val used = manifest.entries.filter(entry => sources.contains(entry.name)).map(entry => s"${entry.name} (sha256 ${entry.sha256})")
    List(
      s"// GENERATED by scripts/unicode (scala-cli run scripts/unicode -- generate) from Unicode ${manifest.version} data - DO NOT EDIT.",
      s"// Sources: ${used.mkString(", ")}",
      "// Unicode data files are © 1991-2025 Unicode, Inc., licensed under the Unicode License v3, see LICENSE-UNICODE.",
    ).mkString("", Eol, Eol)
  }

  /** scalafmt (trailingCommas = multiple) keeps the trailing comma only when the array has more than one element. */
  def chunkArray(name: String, chunks: List[String]): String = {
    val comma = if (chunks.lengthIs > 1) "," else ""
    (List(s"  private val $name: Array[String] = Array(") ++ chunks.map(chunk => s"""    "$chunk"$comma""") ++ List("  )")).mkString(Eol)
  }

  private def constants(objectName: String, names: List[(String, Int)]): String =
    (List(s"  object $objectName {", "") ++ names.flatMap {
      case (name, value) => List(s"    val $name: Int = ${value.toString}", "")
    } ++ List("  }"))
      .mkString(Eol)

  def codePointTable(manifest: Manifest, trie: Trie): String = {
    val version = manifest.version.split('.').toList.map(_.toInt) match {
      case List(major, minor, update) => s"UnicodeVersion(${major.toString}, ${minor.toString}, ${update.toString})"
      case other => s"UnicodeVersion(${other.mkString(", ")})"
    }
    val decode  =
      """  private def decode(chunks: Array[String]): Array[Char] = {
        |    val out     = new Array[Char](chunks.foldLeft(0)((length, chunk) => length + chunk.length))
        |    val offsets = chunks.scanLeft(0)((offset, chunk) => offset + chunk.length)
        |    chunks.zip(offsets).foreach { case (chunk, offset) => chunk.getChars(0, chunk.length, out, offset) }
        |    out.indices.foreach(i => out(i) = (out(i) - 0x20).toChar)
        |    out
        |  }
        |""".stripMargin
    List(
      header(manifest, TableSources),
      "package stui.unicode.internal",
      "",
      "import stui.unicode.UnicodeVersion",
      "",
      "/** Packed per-code-point records behind a two-level trie: Grapheme_Cluster_Break (bits 0..3), Indic_Conjunct_Break (4..5),",
      "  * Extended_Pictographic (6), Emoji_Presentation (7), and the baked display width (8..9). Tables are string-encoded (value + 0x20 per",
      "  * char) and decoded once at class initialisation, which keeps every lookup allocation-free.",
      "  */",
      "private[unicode] object CodePointTable {",
      "",
      s"  val unicodeVersion: UnicodeVersion = $version",
      "",
      constants("Gcb", Gcb.scalaNames),
      "",
      constants("InCB", InCB.scalaNames),
      "",
      s"  val Shift: Int = ${trie.shift.toString}",
      "",
      s"  val Mask: Int = ${((1 << trie.shift) - 1).toString}",
      "",
      chunkArray("IndexChunks", valueChunks(trie.index)),
      "",
      chunkArray("LeafChunks", valueChunks(trie.leaves)),
      "",
      chunkArray("RecordChunks", valueChunks(trie.records)),
      "",
      "  private val Index: Array[Char] = decode(IndexChunks)",
      "",
      "  private val Leaves: Array[Char] = decode(LeafChunks)",
      "",
      "  private val Records: Array[Int] = decode(RecordChunks).map(_.toInt)",
      "",
      "  /** The packed record of `cp`, which must be in 0..0x10FFFF (lone surrogates included). */",
      "  def record(cp: Int): Int = Records(Leaves((Index(cp >> Shift) << Shift) | (cp & Mask)).toInt)",
      "",
      "  def gcb(record: Int): Int = record & 0xf",
      "",
      "  def incb(record: Int): Int = (record >> 4) & 0x3",
      "",
      "  def isExtendedPictographic(record: Int): Boolean = (record & 0x40) > 0",
      "",
      "  def isEmojiPresentation(record: Int): Boolean = (record & 0x80) > 0",
      "",
      "  def width(record: Int): Int = (record >> 8) & 0x3",
      "",
      decode,
      "}",
    ).mkString("", Eol, Eol)
  }

  /** Every table value must fit the `value + 0x20` char encoding, otherwise `encodeValue` would truncate silently. */
  def checkEncodable(trie: Trie): Either[String, Unit] = {
    val tooLarge = List("index" -> trie.index, "leaves" -> trie.leaves, "records" -> trie.records).flatMap {
      case (name, values) =>
        values
          .filter(_ > MaxValue)
          .headOption
          .map(value => s"$name contains ${value.toString}, above the encodable maximum ${MaxValue.toString}")
    }
    if (tooLarge.isEmpty) Right(()) else Left(tooLarge.mkString(", "))
  }

  def corpus(
    manifest: Manifest,
    packageName: String,
    objectName: String,
    doc: String,
    sourceFile: String,
    sha256: String,
    headerSources: List[String],
    lines: List[String],
  ): String = {
    val imports = if (packageName == "stui.unicode.corpus") Nil else List("import stui.unicode.corpus.CorpusLines", "")
    (List(
      header(manifest, headerSources),
      s"package $packageName",
      "",
    ) ++ imports ++ List(
      s"/** $doc */",
      s"object $objectName {",
      "",
      stringVal("sourceFile", sourceFile),
      "",
      stringVal("sha256", sha256),
      "",
      chunkArray("Chunks", lineChunks(lines).map(escape)),
      "",
      "  val lines: Vector[String] = CorpusLines.split(Chunks)",
      "",
      "}",
    )).mkString("", Eol, Eol)
  }

  /** scalafmt (maxColumn 140) moves a string literal to its own line when the one-line `val` would be longer than that. */
  def stringVal(name: String, value: String): String = {
    val oneLine = s"""  val $name: String = "$value""""
    if (oneLine.length <= MaxColumn) oneLine else s"""  val $name: String =$Eol    "$value""""
  }

  private def sha256Of(manifest: Manifest, name: String): String = manifest.entries.find(_.name == name).map(_.sha256).getOrElse("unknown")

  def outputs(manifest: Manifest, data: UcdData, records: Array[Int], trie: Trie): List[Output] =
    List(
      Output(CodePointTablePath, codePointTable(manifest, trie)),
      Output(
        GraphemeBreakTestCorpusPath,
        corpus(
          manifest,
          "stui.unicode.corpus",
          "GraphemeBreakTestCorpus",
          "The data part of every test line of GraphemeBreakTest.txt (`÷` break, `×` no break, hex code points), parsed by GraphemeBreakCase.",
          "GraphemeBreakTest.txt",
          sha256Of(manifest, "GraphemeBreakTest.txt"),
          List("GraphemeBreakTest.txt"),
          data.graphemeBreakTestLines,
        ),
      ),
      Output(
        EmojiTestCorpusPath,
        corpus(
          manifest,
          "stui.unicode.corpus",
          "EmojiTestCorpus",
          "Every fully-qualified emoji of emoji-test.txt as space-separated hex code points.",
          "emoji-test.txt",
          sha256Of(manifest, "emoji-test.txt"),
          List("emoji-test.txt"),
          data.emojiTestLines,
        ),
      ),
      Output(
        RawRangesPath,
        corpus(
          manifest,
          "stui.unicode.internal",
          "RawRanges",
          "Run-length encoded records straight from the parsed UCD data (`START..END;GCB;INCB;EP;EMOJIPRESENTATION;WIDTH`), independent of the trie.",
          TableSources.mkString(", "),
          TableSources.map(name => sha256Of(manifest, name)).mkString(", "),
          TableSources,
          Tables.rawRanges(records),
        ),
      ),
    )

}
