name: Build

on:
  push:
    branches-ignore:
      - main

  pull_request:
    branches:
      - main

env:
  SBT_OPTS: "-Xss64m -Xmx4G"
  JVM_OPTS: "-Xss64m -Xmx4G"

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: sbt

      - uses: sbt/setup-sbt@v1

      - uses: VirtusLab/scala-cli-setup@v1.16.0

      - name: "Check the UCD generator formats and compiles"
        run: |
          scala-cli fmt --check --scalafmt-conf .scalafmt.conf scripts/unicode
          scala-cli compile scripts/unicode

      - uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: "Build and test all platforms on ${{ matrix.os }} - ${{ github.run_number }}"
        run: |
          java -version
          node --version
          sbt -v clean scalafmtCheckAll scalafmtSbtCheck "scalafixAll --check" test
